version: '2'
services:
  codereview:
    build:
      context: ../.
      dockerfile: docker/Dockerfile
      args:
        - userid
    volumes:
      - ../:/srv/app
    environment:
      - DEBUG=1
      - CONFIG_CACHE_ENABLED=0
      - COMPOSER_HOME=/srv/app/.composer
    working_dir: /srv/app
